### ISSUE TITLE
感谢开源 ，我在使用时遇到了一个问题

### ISSUE THREAD

**Issue by imphila** [wanyakun/pod-template#1]
模板创建的工程fastlane build_lib 报错 fastlane build_fmk 没有问题

```
philia@philiadeMacBook-Pro testLibrary % pod lib create --template-url=https://github.com/wanyakun/pod-template.git MyLibrary

Cloning `https://github.com/wanyakun/pod-template.git` into `MyLibrary`.
Configuring MyLibrary template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide:
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and click links to open in a browser. )


What language do you want to use?? [ Swift / ObjC ]
 > objc

Would you like to include a demo application with your library? [ Yes / No ]
 > yes

Which testing frameworks will you use? [ Specta / Kiwi / None ]
 > none

Would you like to do view based testing? [ Yes / No ]
 > no

What is your class prefix?
 > TEST

Running pod install on your new library.

Analyzing dependencies
Downloading dependencies
Installing MyLibrary (0.0.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `MyLibrary.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'MyLibrary/Example/MyLibrary.xcworkspace'

To learn more about the template see `https://github.com/wanyakun/pod-template.git`.
To learn more about creating a new pod, see `https://guides.cocoapods.org/making/making-a-cocoapod`.
philia@philiadeMacBook-Pro testLibrary % ls
MyLibrary
philia@philiadeMacBook-Pro testLibrary % cd MyLibrary
philia@philiadeMacBook-Pro MyLibrary % fastlane build_lib
[✔] 🚀
[16:51:15]: fastlane detected a Gemfile in the current directory
[16:51:15]: However, it seems like you didn't use `bundle exec`
[16:51:15]: To launch fastlane faster, please use
[16:51:15]:
[16:51:15]: $ bundle exec fastlane build_lib
[16:51:15]:
[16:51:15]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:51:16]: -----------------------------
[16:51:16]: --- Step: import_from_git ---
[16:51:16]: -----------------------------
[16:51:16]: Cloning remote git repo...
[16:51:16]: $ git clone https://github.com/wanyakun/fastlane.git /var/folders/_9/dhsbq9gd40bbzvc4y2ngv30w0000gq/T/fl_clone20200115-95693-ng1914/fastlane.git --depth 1 -n --branch master
[16:51:16]: ▸ Cloning into '/var/folders/_9/dhsbq9gd40bbzvc4y2ngv30w0000gq/T/fl_clone20200115-95693-ng1914/fastlane.git'...
[16:51:20]: $ cd /var/folders/_9/dhsbq9gd40bbzvc4y2ngv30w0000gq/T/fl_clone20200115-95693-ng1914/fastlane.git && git checkout master fastlane/Fastfile
[16:51:20]: $ cd /var/folders/_9/dhsbq9gd40bbzvc4y2ngv30w0000gq/T/fl_clone20200115-95693-ng1914/fastlane.git && git checkout master fastlane/actions
[16:51:20]: ------------------------------
[16:51:20]: --- Step: default_platform ---
[16:51:20]: ------------------------------
[16:51:20]: ------------------------------
[16:51:20]: --- Step: default_platform ---
[16:51:20]: ------------------------------
[16:51:20]: Driving the lane 'ios build_lib' 🚀
[16:51:20]: ---------------------------------
[16:51:20]: --- Step: yk_build_static_lib ---
[16:51:20]: ---------------------------------
[16:51:20]: $ xcodebuild clean archive -project /Users/philia/Desktop/iOS/testLibrary/MyLibrary/Example/Pods/Pods.xcodeproj -scheme MyLibrary -configuration Release -sdk iphoneos OBJROOT=/Users/philia/Desktop/iOS/testLibrary/MyLibrary/build SYMROOT=/Users/philia/Desktop/iOS/testLibrary/MyLibrary/build ONLY_ACTIVE_ARCH=NO | xcpretty
[16:51:23]: ▸ Clean Succeeded
[16:51:23]: ▸ Copying MyLibrary-umbrella.h
[16:51:23]: ▸ Processing MyLibrary-Info.plist
[16:51:23]: ▸ Compiling ReplaceMe.m
[16:51:23]: ▸ Compiling MyLibrary-dummy.m
[16:51:23]: ▸ Compiling ReplaceMe.m
[16:51:23]: ▸ Compiling MyLibrary-dummy.m
[16:51:23]: ▸ Compiling MyLibrary_vers.c
[16:51:23]: ▸ Compiling MyLibrary_vers.c
[16:51:23]: ▸ Linking MyLibrary
[16:51:24]: ▸ Linking MyLibrary
[16:51:24]: ▸ Generating 'MyLibrary.framework.dSYM'
[16:51:24]: ▸ Touching MyLibrary.framework (in target 'MyLibrary' from project 'Pods')
[16:51:24]: ▸ Archive Succeeded
[16:51:24]: $ cp -R /Users/philia/Desktop/iOS/testLibrary/MyLibrary/build/UninstalledProducts/iphoneos/ /Users/philia/Desktop/iOS/testLibrary/MyLibrary/lib/
[16:51:24]: $ cp -r /Users/philia/Desktop/iOS/testLibrary/MyLibrary/Example/Pods/Headers/Public/MyLibrary/ /Users/philia/Desktop/iOS/testLibrary/MyLibrary/lib/MyLibrary/
[16:51:24]: ▸ cp: directory /Users/philia/Desktop/iOS/testLibrary/MyLibrary/lib/MyLibrary does not exist
+------------------+---------------+
|           Lane Context           |
+------------------+---------------+
| DEFAULT_PLATFORM | ios           |
| PLATFORM_NAME    | ios           |
| LANE_NAME        | ios build_lib |
+------------------+---------------+
[16:51:24]: Exit status of command 'cp -r /Users/philia/Desktop/iOS/testLibrary/MyLibrary/Example/Pods/Headers/Public/MyLibrary/ /Users/philia/Desktop/iOS/testLibrary/MyLibrary/lib/MyLibrary/' was 1 instead of 0.
cp: directory /Users/philia/Desktop/iOS/testLibrary/MyLibrary/lib/MyLibrary does not exist


+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 2    | import_from_git     | 3           |
| 3    | default_platform    | 0           |
| 💥   | yk_build_static_lib | 3           |
+------+---------------------+-------------+

[16:51:24]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	30: from /usr/local/bin/fastlane:23:in `<main>'
	29: from /usr/local/bin/fastlane:23:in `load'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	22: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	12: from Fastfile:22:in `block (2 levels) in parsing_binding'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 4: from /var/folders/_9/dhsbq9gd40bbzvc4y2ngv30w0000gq/T/fl_clone20200115-95693-ng1914/fastlane.git/fastlane/actions/yk_build_static_lib.rb:36:in `run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'cp -r /Users/philia/Desktop/iOS/testLibrary/MyLibrary/Example/Pods/Headers/Public/MyLibrary/ /Users/philia/Desktop/iOS/testLibrary/MyLibrary/lib/MyLibrary/' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
cp: directory /Users/philia/Desktop/iOS/testLibrary/MyLibrary/lib/MyLibrary does not exist

philia@philiadeMacBook-Pro MyLibrary % fastlane build_fmk
[✔] 🚀
[16:51:40]: fastlane detected a Gemfile in the current directory
[16:51:40]: However, it seems like you didn't use `bundle exec`
[16:51:40]: To launch fastlane faster, please use
[16:51:40]:
[16:51:40]: $ bundle exec fastlane build_fmk
[16:51:40]:
[16:51:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:51:42]: -----------------------------
[16:51:42]: --- Step: import_from_git ---
[16:51:42]: -----------------------------
[16:51:42]: Cloning remote git repo...
[16:51:42]: $ git clone https://github.com/wanyakun/fastlane.git /var/folders/_9/dhsbq9gd40bbzvc4y2ngv30w0000gq/T/fl_clone20200115-95772-vccaa/fastlane.git --depth 1 -n --branch master
[16:51:42]: ▸ Cloning into '/var/folders/_9/dhsbq9gd40bbzvc4y2ngv30w0000gq/T/fl_clone20200115-95772-vccaa/fastlane.git'...
[16:51:45]: $ cd /var/folders/_9/dhsbq9gd40bbzvc4y2ngv30w0000gq/T/fl_clone20200115-95772-vccaa/fastlane.git && git checkout master fastlane/Fastfile
[16:51:45]: $ cd /var/folders/_9/dhsbq9gd40bbzvc4y2ngv30w0000gq/T/fl_clone20200115-95772-vccaa/fastlane.git && git checkout master fastlane/actions
[16:51:45]: ------------------------------
[16:51:45]: --- Step: default_platform ---
[16:51:45]: ------------------------------
[16:51:45]: ------------------------------
[16:51:45]: --- Step: default_platform ---
[16:51:45]: ------------------------------
[16:51:45]: Driving the lane 'ios build_fmk' 🚀
[16:51:45]: --------------------------------
[16:51:45]: --- Step: yk_build_framework ---
[16:51:45]: --------------------------------
[16:51:45]: $ xcodebuild clean archive -project /Users/philia/Desktop/iOS/testLibrary/MyLibrary/Example/Pods/Pods.xcodeproj -scheme MyLibrary -configuration Release -sdk iphoneos OBJROOT=/Users/philia/Desktop/iOS/testLibrary/MyLibrary/build SYMROOT=/Users/philia/Desktop/iOS/testLibrary/MyLibrary/build ONLY_ACTIVE_ARCH=NO | xcpretty
[16:51:48]: ▸ Clean Succeeded
[16:51:48]: ▸ Processing MyLibrary-Info.plist
[16:51:48]: ▸ Copying MyLibrary-umbrella.h
[16:51:48]: ▸ Compiling ReplaceMe.m
[16:51:48]: ▸ Compiling MyLibrary-dummy.m
[16:51:48]: ▸ Compiling MyLibrary-dummy.m
[16:51:48]: ▸ Compiling ReplaceMe.m
[16:51:48]: ▸ Compiling MyLibrary_vers.c
[16:51:48]: ▸ Compiling MyLibrary_vers.c
[16:51:48]: ▸ Linking MyLibrary
[16:51:48]: ▸ Linking MyLibrary
[16:51:48]: ▸ Generating 'MyLibrary.framework.dSYM'
[16:51:48]: ▸ Touching MyLibrary.framework (in target 'MyLibrary' from project 'Pods')
[16:51:48]: ▸ Archive Succeeded
[16:51:49]: $ cp -R /Users/philia/Desktop/iOS/testLibrary/MyLibrary/build/UninstalledProducts/iphoneos/MyLibrary.framework /Users/philia/Desktop/iOS/testLibrary/MyLibrary/fmk/
[16:51:49]: $ cp -R /Users/philia/Desktop/iOS/testLibrary/MyLibrary/build/Release-iphoneos/MyLibrary/MyLibrary.framework.dSYM /Users/philia/Desktop/iOS/testLibrary/MyLibrary/fmk/
[16:51:49]: $ xcodebuild clean build -project /Users/philia/Desktop/iOS/testLibrary/MyLibrary/Example/Pods/Pods.xcodeproj -scheme MyLibrary -configuration Release -sdk iphonesimulator OBJROOT=/Users/philia/Desktop/iOS/testLibrary/MyLibrary/build SYMROOT=/Users/philia/Desktop/iOS/testLibrary/MyLibrary/build ONLY_ACTIVE_ARCH=NO | xcpretty
[16:51:50]: ▸ Clean Succeeded
[16:51:51]: ▸ Copying MyLibrary-umbrella.h
[16:51:51]: ▸ Processing MyLibrary-Info.plist
[16:51:51]: ▸ Compiling MyLibrary-dummy.m
[16:51:51]: ▸ Compiling ReplaceMe.m
[16:51:51]: ▸ Compiling ReplaceMe.m
[16:51:51]: ▸ Compiling MyLibrary-dummy.m
[16:51:51]: ▸ Compiling MyLibrary_vers.c
[16:51:51]: ▸ Compiling MyLibrary_vers.c
[16:51:51]: ▸ Linking MyLibrary
[16:51:51]: ▸ Linking MyLibrary
[16:51:51]: ▸ Generating 'MyLibrary.framework.dSYM'
[16:51:51]: ▸ Touching MyLibrary.framework (in target 'MyLibrary' from project 'Pods')
[16:51:51]: ▸ Build Succeeded
[16:51:51]: $ lipo -create -output /Users/philia/Desktop/iOS/testLibrary/MyLibrary/fmk/MyLibrary.framework/MyLibrary /Users/philia/Desktop/iOS/testLibrary/MyLibrary/build/Release-iphonesimulator/MyLibrary/MyLibrary.framework/MyLibrary /Users/philia/Desktop/iOS/testLibrary/MyLibrary/fmk/MyLibrary.framework/MyLibrary
[16:51:51]: $ rm -rf /Users/philia/Desktop/iOS/testLibrary/MyLibrary/build

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | default_platform   | 0           |
| 2    | import_from_git    | 3           |
| 3    | default_platform   | 0           |
| 4    | yk_build_framework | 5           |
+------+--------------------+-------------+

[16:51:51]: fastlane.tools finished successfully
```

请看看是什么原因呀！

**Comment by imphila** [comment]
我知道了 在podfile里需要把 use_frameworks! 注释就可以了
